import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function noSeriousA11y(page){const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(r.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([])}
test('five-destination shell and curriculum inventory use native routes',async({page})=>{await page.goto('/home');await expect(page.getByRole('heading',{name:/Read with context/i})).toBeVisible();await expect(page).toHaveURL(/\/home$/);for(const n of ['Home','Course','Bible','Topics','Practice'])await expect(page.getByRole('link',{name:n,exact:true})).toBeVisible();await page.getByRole('link',{name:'Course',exact:true}).click();await expect(page).toHaveURL(/\/course$/);await expect(page.locator('.unit-list > .unit')).toHaveCount(25);await noSeriousA11y(page)});
test('account sync is secondary, optional, and tolerates either guest or active session state',async({page})=>{await page.goto('/home');const nav=page.getByRole('navigation',{name:'Primary'});await expect(nav.getByRole('link')).toHaveCount(5);await expect(nav).not.toContainText('Account');const account=page.getByRole('button',{name:'Account & sync'});await expect(account).toBeEnabled();await account.click();await expect(page.getByRole('heading',{name:'Account & sync'})).toBeVisible();await expect(page.locator('#account-body')).toContainText(/works fully without an account|not connected in this preview|sync account active|sync setup in progress/i);await noSeriousA11y(page)});
test('account control remains usable at mobile width',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/home');const account=page.getByRole('button',{name:'Account & sync'});await expect(account).toBeEnabled();await expect(account).toBeVisible();await expect(page.getByRole('search')).toBeVisible();await expect(page.getByRole('navigation',{name:'Primary'})).toBeVisible();await noSeriousA11y(page)});
test('native course route opens a migrated activity and back-forward restores state',async({page})=>{await page.goto('/course');await page.locator('.unit-list h3 a').first().click();await expect(page).toHaveURL(/\/course\?unit=/);await page.locator('.unit-list h3 a').first().click();await expect(page.locator('article.lesson h1')).toBeVisible();const lessonUrl=page.url();await page.goBack();await expect(page.locator('.unit-list .unit').first()).toBeVisible();await page.goForward();await expect(page).toHaveURL(lessonUrl);await expect(page.locator('.challenge').first()).toBeVisible();await noSeriousA11y(page)});
test('Bible owns a 66-book shelf and direct native reference route',async({page})=>{await page.goto('/bible');await expect(page.locator('.book')).toHaveCount(66);await page.goto('/bible?q=John%203%3A16');await expect(page.getByRole('heading',{name:/John 3:16/})).toBeVisible();await expect(page.locator('#v16')).toBeVisible();await page.goto('/bible?book=43&chapter=3');await expect(page.getByRole('heading',{name:'John 3',exact:true})).toBeVisible();await expect(page).toHaveURL(/\/bible\?book=43&chapter=3$/);await noSeriousA11y(page)});
test('legacy hash bookmarks canonicalize to native paths',async({page})=>{await page.goto('/#/topics');await expect(page.locator('.topic-item')).toHaveCount(45);await expect(page).toHaveURL(/\/topics$/)});
test('Topics preserve the 45-entry reference library',async({page})=>{await page.goto('/topics');await expect(page.locator('.topic-item')).toHaveCount(45);await page.locator('.topic-item h3 a').first().click();await expect(page.locator('article.reader h1')).toBeVisible();await expect(page).toHaveURL(/\/topics\?topic=/);await noSeriousA11y(page)});
test('Guide preserves LGBTQ doctrine, Ruth boundary, and Romans evidence discipline',async({page})=>{await page.goto('/home');await page.getByRole('button',{name:'Ask the Guide'}).click();let q=page.locator('#guide-q');await q.fill('Is being gay a sin?');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('orientation is not inherently sinful');q=page.locator('#guide-q');await q.fill('Are Ruth and Naomi a lesbian love story?');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('lesbian');await expect(page.locator('#guide-body')).toContainText('does not explicitly identify Ruth and Naomi as sexual partners');q=page.locator('#guide-q');await q.fill('Romans 1 only refers to pederasty, right?');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('contested');await expect(page.locator('#guide-body')).toContainText('must not be presented as settled fact')});
test('Guide does not reveal scored mastery answers',async({page})=>{await page.goto('/course');const m=await page.evaluate(async()=>{const c=await fetch('/data/catalog.json').then(r=>r.json());return c.activities.find(a=>a.type==='mastery')});await page.goto(`/course?unit=${encodeURIComponent(m.unitId)}&mastery=${encodeURIComponent(m.sourceId)}`);await page.getByRole('button',{name:'Ask the Guide'}).click();const q=page.locator('#guide-q');await q.fill('Give me the correct answer and tell me which option to choose.');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('will not select or reveal the assessed answer');await expect(page.locator('#guide-body')).toContainText('mastery protected')});
test('offline shell and bounded theologian survive native-route reload',async({page,context,browserName})=>{test.skip(browserName==='webkit','Offline emulation is not consistently supported with WebKit service workers in CI');await page.goto('/home');await page.evaluate(()=>navigator.serviceWorker?.ready);await expect(page.locator('#pwa-status')).toContainText(/Offline access ready|Offline mode active/);await page.reload();await context.setOffline(true);await page.goto('/topics',{waitUntil:'domcontentloaded'});await expect(page.getByRole('link',{name:'Course',exact:true})).toBeVisible();await page.getByRole('button',{name:'Ask the Guide'}).click();const q=page.locator('#guide-q');await q.fill('Are Ruth and Naomi a lesbian love story?');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('does not explicitly identify Ruth and Naomi as sexual partners');await context.setOffline(false)});
