import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function noSeriousA11y(page){const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(r.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([])}
test('five-destination shell and curriculum inventory',async({page})=>{await page.goto('/#/home');await expect(page.getByRole('heading',{name:/Read with context/i})).toBeVisible();for(const n of ['Home','Course','Bible','Topics','Practice'])await expect(page.getByRole('link',{name:n,exact:true})).toBeVisible();await page.goto('/#/course');await expect(page.locator('.unit-list > .unit')).toHaveCount(25);await noSeriousA11y(page)});
test('course opens a migrated activity',async({page})=>{await page.goto('/#/course');await page.locator('.unit-list h3 a').first().click();await expect(page.locator('.unit-list .unit').first()).toBeVisible();await page.locator('.unit-list h3 a').first().click();await expect(page.locator('article.lesson h1')).toBeVisible();await expect(page.locator('.challenge').first()).toBeVisible();await noSeriousA11y(page)});
test('Bible owns a 66-book shelf and direct reference reader',async({page})=>{await page.goto('/#/bible');await expect(page.locator('.book')).toHaveCount(66);await page.goto('/#/bible?q=John%203%3A16');await expect(page.getByRole('heading',{name:/John 3:16/})).toBeVisible();await expect(page.locator('#v16')).toBeVisible();await page.goto('/#/bible?book=43&chapter=3');await expect(page.getByRole('heading',{name:'John 3',exact:true})).toBeVisible();await noSeriousA11y(page)});
test('Topics preserve the 45-entry reference library',async({page})=>{await page.goto('/#/topics');await expect(page.locator('.topic-item')).toHaveCount(45);await page.locator('.topic-item h3 a').first().click();await expect(page.locator('article.reader h1')).toBeVisible();await noSeriousA11y(page)});
test('Guide preserves LGBTQ doctrine and Ruth evidence boundary',async({page})=>{await page.goto('/#/home');await page.getByRole('button',{name:'Ask the Guide'}).click();let q=page.locator('#guide-q');await q.fill('Is being gay a sin?');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('orientation is not inherently sinful');q=page.locator('#guide-q');await q.fill('Are Ruth and Naomi a lesbian love story?');await page.locator('#guide-form').getByRole('button',{name:'Ask'}).click();await expect(page.locator('#guide-body')).toContainText('lesbian');await expect(page.locator('#guide-body')).toContainText('does not explicitly identify Ruth and Naomi as sexual partners')});
test('offline shell survives reload after service worker activation',async({page,context,browserName})=>{test.skip(browserName==='webkit','Offline emulation is not consistently supported with WebKit service workers in CI');await page.goto('/#/home');await page.evaluate(()=>navigator.serviceWorker?.ready);await page.reload();await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await expect(page.getByRole('link',{name:'Course',exact:true})).toBeVisible();await context.setOffline(false)});
