// Builds public/ui/shell.css from public/ui/src/*.src.css. Lengths are written in board units: 12u becomes
// calc(12 * var(--u)), the way docs/design/templates/build.mjs does it, so the app's screens move over from the
// templates without rewriting a length. Run `bun scripts/build-ui-css.mjs` (or with --check to fail when stale).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'public/ui/src');
// Output file -> source parts, in cascade order.
// A part list builds into @layer components; { layer, parts } picks another layer (screens, for a screen's sheet).
const OUTPUTS = {
  'public/ui/shell.css': ['tokens.src.css', 'shell.src.css'],
  'public/ui/components/edge-tab.css': ['edge-tab.src.css'],
  'public/ui/screens/lesson.css': { layer: 'screens', parts: ['lesson.src.css'] },
  'public/ui/screens/practice.css': { layer: 'screens', parts: ['practice.src.css'] },
  'public/ui/screens/topics.css': { layer: 'screens', parts: ['topics.src.css'] },
  'public/ui/screens/learning-path.css': { layer: 'screens', parts: ['path.src.css'] },
  'public/ui/screens/reader.css': { layer: 'screens', parts: ['reader.src.css'] }
};
const units = /(^|[^\w.#-])(-?\d*\.?\d+)u(?![\w-])/g;
const check = process.argv.includes('--check');
let stale = 0;

for (const [out, spec] of Object.entries(OUTPUTS)) {
  const parts = Array.isArray(spec) ? spec : spec.parts;
  const layer = Array.isArray(spec) ? 'components' : spec.layer;
  const body = parts.map(name => readFileSync(join(src, name), 'utf8')).join('\n')
    .replace(units, (_, lead, n) => `${lead}calc(${n} * var(--u))`);
  const css = `/* Generated by scripts/build-ui-css.mjs from public/ui/src. Do not edit by hand. */\n@layer ${layer} {\n${body}\n}\n`;
  const path = join(root, out);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== css) { console.error(`build-ui-css: ${out} is stale; run bun scripts/build-ui-css.mjs`); stale++; }
  } else { writeFileSync(path, css); console.log(`built ${out}`); }
}
if (stale) process.exit(1);
