// Builds public/ui/shell.css from public/ui/src/*.src.css. Lengths are written in board units: 12u becomes
// calc(12 * var(--u)), the way docs/design/templates/build.mjs does it, so the app's screens move over from the
// templates without rewriting a length. Run `bun scripts/build-ui-css.mjs` (or with --check to fail when stale).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'public/ui/src');
// Output file -> source parts, in cascade order.
const OUTPUTS = {
  'public/ui/shell.css': ['tokens.src.css', 'shell.src.css'],
  'public/ui/components/edge-tab.css': ['edge-tab.src.css']
};
const units = /(^|[^\w.#-])(-?\d*\.?\d+)u(?![\w-])/g;
const check = process.argv.includes('--check');
let stale = 0;

for (const [out, parts] of Object.entries(OUTPUTS)) {
  const body = parts.map(name => readFileSync(join(src, name), 'utf8')).join('\n')
    .replace(units, (_, lead, n) => `${lead}calc(${n} * var(--u))`);
  const css = `/* Generated by scripts/build-ui-css.mjs from public/ui/src. Do not edit by hand. */\n@layer components {\n${body}\n}\n`;
  const path = join(root, out);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== css) { console.error(`build-ui-css: ${out} is stale; run bun scripts/build-ui-css.mjs`); stale++; }
  } else { writeFileSync(path, css); console.log(`built ${out}`); }
}
if (stale) process.exit(1);
