// Downloads each theme's fonts (theme contract: themes.*.fontSources) and writes a self-hosted stylesheet.
// Fonts are served from this site so visitors' browsers never contact a third party (privacy posture), and the
// Content-Security-Policy stays 'self'-only. Only Latin subsets are kept. All fonts used are SIL Open Font License.
// Run: bun run fonts:fetch   (re-run after changing a theme's fontSources)
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';

const OUT = 'public/fonts';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);
const themes = JSON.parse(readFileSync('.roa/values/theme.json', 'utf8')).themes;
const sources = [...new Set(Object.values(themes).flatMap(t => t.fontSources || []))];
mkdirSync(OUT, { recursive: true });
const used = new Set();
const faces = [];
for (const url of sources) {
  const css = await (await fetch(url, { headers: { 'user-agent': UA } })).text();
  for (const m of css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
    if (!KEEP.has(m[1])) continue;
    let block = m[2];
    const src = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!src) continue;
    const name = `${createHash('sha256').update(src).digest('hex').slice(0, 16)}.woff2`;
    if (!existsSync(`${OUT}/${name}`)) writeFileSync(`${OUT}/${name}`, Buffer.from(await (await fetch(src, { headers: { 'user-agent': UA } })).arrayBuffer()));
    used.add(name);
    faces.push(`/* ${m[1]} */\n` + block.replace(src, `/fonts/${name}`));
  }
}
for (const f of readdirSync(OUT)) if (f.endsWith('.woff2') && !used.has(f)) rmSync(`${OUT}/${f}`);
// Faces that are not fetched (public/fonts/local/faces.css) go last, so they win over a fetched face of the same family.
const local = existsSync(`${OUT}/local/faces.css`) ? readFileSync(`${OUT}/local/faces.css`, 'utf8') : '';
writeFileSync(`${OUT}/fonts.css`, `/* GENERATED by scripts/fetch-fonts.mjs from the theme contract's fontSources and public/fonts/local/faces.css. SIL Open Font License fonts, self-hosted. */\n${faces.join('\n')}\n${local}`);
console.log(`fonts: ${faces.length} faces, ${used.size} files from ${sources.length} theme sources`);
