import {mergeLearnerState,remoteSnapshot,recordMutation,acknowledgeSync,createSyncMeta} from '../public/sync.js';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const base=(device)=>({version:3,completed:[],attempts:{},mastery:{},reviews:{},reviewSchedule:{},notes:{},journal:{},migrations:{},legacyRaw:{secret:'legacy'},sync:createSyncMeta({deviceId:device,clocks:{},outbox:[]}),updatedAt:'2026-09-16T12:00:00.000Z'});
const a=base('device-a'),b=base('device-b');
a.completed=['lesson:a'];a.attempts['lesson:a']=2;a.reviewSchedule['lesson:a']={stage:1,dueAt:'2026-09-20T00:00:00.000Z',intervalDays:3};a.sync.clocks['result:lesson:a']='2026-09-16T13:00:00.000Z';
b.completed=['mastery:b'];b.attempts['mastery:b']=1;b.mastery['mastery:b']={passed:true,attempts:1,lastAttempt:'2026-09-16T14:00:00.000Z'};b.reviewSchedule['lesson:a']={stage:0,dueAt:'2026-09-18T00:00:00.000Z',intervalDays:1};b.sync.clocks['review:lesson:a']='2026-09-16T15:00:00.000Z';
a.notes['lesson:a']={text:'older note',updatedAt:'2026-09-16T12:30:00.000Z'};
b.notes['lesson:a']={text:'newer note',updatedAt:'2026-09-16T15:30:00.000Z'};
a.journal['lesson:a']={text:'newer journal',updatedAt:'2026-09-16T16:00:00.000Z'};
b.journal['lesson:a']={text:'older journal',updatedAt:'2026-09-16T11:00:00.000Z'};
const merged=mergeLearnerState(a,b);
assert(merged.completed.includes('lesson:a')&&merged.completed.includes('mastery:b'),'offline completion union failed');
assert(merged.mastery['mastery:b']?.passed===true,'mastery pass must survive merge');
assert(merged.reviewSchedule['lesson:a'].stage===0,'newer review reset must win over older higher stage');
assert(merged.notes['lesson:a']?.text==='newer note','newer personal note did not win merge');
assert(merged.journal['lesson:a']?.text==='newer journal','newer journal did not win merge');
assert(merged.sync.deviceId==='device-a','merge must retain local device identity');
const snap=remoteSnapshot(merged);assert(!('legacyRaw'in snap),'legacy raw data must never enter remote sync snapshot');assert(!('outbox'in(snap.sync||{})),'local outbox must never be nested in remote snapshot');assert(snap.notes['lesson:a']?.text==='newer note','notes missing from sync snapshot');assert(snap.journal['lesson:a']?.text==='newer journal','journal missing from sync snapshot');
recordMutation(merged,'result',{id:'lesson:c',passed:true},'2026-09-16T16:00:00.000Z');const event=merged.sync.outbox.at(-1);assert(event.deviceId==='device-a','mutation device identity missing');
acknowledgeSync(merged,{cursor:'c1',acceptedIds:[event.id]});assert(!merged.sync.outbox.some(x=>x.id===event.id),'acknowledged mutation remained in outbox');assert(merged.sync.cursor==='c1','sync cursor not advanced');
console.log('v7 sync merge/privacy/personal-writing/outbox gates passed');
