import {mergeLearnerState,remoteSnapshot,recordMutation,acknowledgeSync,createSyncMeta} from '../public/sync.js';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const base=(device)=>({version:3,completed:[],attempts:{},mastery:{},reviews:{},reviewSchedule:{},notes:{},journal:{},migrations:{},legacyRaw:{secret:'legacy'},sync:createSyncMeta({deviceId:device,clocks:{},outbox:[]}),updatedAt:'2026-09-16T12:00:00.000Z'});
const a=base('device-a'),b=base('device-b');
a.completed=['lesson:a'];a.attempts['lesson:a']=2;a.reviewSchedule['lesson:a']={stage:1,dueAt:'2026-09-20T00:00:00.000Z',intervalDays:3};a.sync.clocks['result:lesson:a']='2026-09-16T13:00:00.000Z';
b.completed=['mastery:b'];b.attempts['mastery:b']=1;b.mastery['mastery:b']={passed:true,attempts:1,lastAttempt:'2026-09-16T14:00:00.000Z'};b.reviewSchedule['lesson:a']={stage:0,dueAt:'2026-09-18T00:00:00.000Z',intervalDays:1};b.sync.clocks['review:lesson:a']='2026-09-16T15:00:00.000Z';
a.notes['lesson:a']={text:'older note',updatedAt:'2026-09-16T12:30:00.000Z'};
b.notes['lesson:a']={text:'newer note',updatedAt:'2026-09-16T15:30:00.000Z'};
a.journal['lesson:a']={text:'newer journal',updatedAt:'2026-09-16T16:00:00.000Z'};
b.journal['lesson:a']={text:'older journal',updatedAt:'2026-09-16T11:00:00.000Z'};
const merged=mergeLearnerState(a,b);
assert(merged.completed.includes('lesson:a')&&merged.completed.includes('mastery:b'),'offline completion union failed');
assert(merged.mastery['mastery:b']?.passed===true,'mastery pass must survive merge');
assert(merged.reviewSchedule['lesson:a']?.dueAt===b.reviewSchedule['lesson:a'].dueAt,'newer review record did not win merge');
assert(merged.notes['lesson:a']?.text===b.notes['lesson:a'].text,'newer personal note did not win merge');
assert(merged.journal['lesson:a']?.text===a.journal['lesson:a'].text,'newer journal did not win merge');
assert(merged.sync.deviceId===a.sync.deviceId,'merge did not retain local device identity');
const snap=remoteSnapshot(merged);
assert(!('legacyRaw'in snap),'local migration data entered remote sync snapshot');
assert(!('outbox'in(snap.sync||{})),'local sync outbox entered remote snapshot');
assert(snap.notes['lesson:a']?.text===merged.notes['lesson:a']?.text,'notes missing from sync snapshot');
assert(snap.journal['lesson:a']?.text===merged.journal['lesson:a']?.text,'journal missing from sync snapshot');
recordMutation(merged,'result',{id:'lesson:c',passed:true},'2026-09-16T16:00:00.000Z');
const event=merged.sync.outbox.at(-1);
assert(event?.deviceId===merged.sync.deviceId,'mutation device identity missing');
acknowledgeSync(merged,{cursor:'cursor-next',acceptedIds:[event.id]});
assert(!merged.sync.outbox.some(item=>item.id===event.id),'acknowledged mutation remained in outbox');
assert(merged.sync.cursor==='cursor-next','sync cursor not advanced');
console.log('PASS — sync merge, privacy, personal-writing, identity, and outbox behavior.');
